image: "teuteuf/unity:latest"

stages:
- check
- test
- build
- post-build

variables:
  BUILD_NAME: SpotTheDefuser

.unity_before_script: &unity_before_script
  before_script:
  - mkdir -p /root/.cache/unity3d
  - mkdir -p /root/.local/share/unity3d/Unity/
  - echo "$UNITY_LICENSE_CONTENT" | tr -d '\r' > /root/.local/share/unity3d/Unity/Unity_lic.ulf

check-cleanarchi:
  image: alpine:latest
  stage: check
  script: | 
    chmod +x Tools/checkCleanArchitecture.sh
    ./Tools/checkCleanArchitecture.sh

.test: &test
  stage: test
  <<: *unity_before_script
  script: |
    xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
      /opt/Unity/Editor/Unity \
        -projectPath $(pwd) \
        -runTests \
        -testPlatform $TEST_PLATFORM \
        -testResults $(pwd)/$TEST_PLATFORM-results.xml \
        -batchmode

  artifacts:
    paths:
    - $(pwd)/$TEST_PLATFORM-results.xml

test-editmode:
  <<: *test
  variables:
    TEST_PLATFORM: editmode

test-playmode:
  <<: *test
  variables:
    TEST_PLATFORM: playmode

.build: &build
  stage: build
  <<: *unity_before_script
  variables:
  script: |
    echo "Building for $BUILD_TARGET"
    export BUILD_PATH=./Builds/$BUILD_TARGET/
    mkdir -p $BUILD_PATH
    xvfb-run --server-args="-screen 0 1024x768x24" \
      /opt/Unity/Editor/Unity \
      -projectPath $(pwd) \
      -quit \
      -batchmode \
      -buildTarget $BUILD_TARGET \
      -customBuildTarget $BUILD_TARGET \
      -customBuildName $BUILD_NAME \
      -customBuildPath $BUILD_PATH \
      -customBuildOptions AcceptExternalModificationsToPlayer \
      -executeMethod BuildCommand.PerformBuild \
      -logFile
    ls -la $BUILD_PATH
    [ -n "$(ls -A $BUILD_PATH)" ] # fail job if build folder is empty

  artifacts:
    paths:
    - ./Builds/

build-StandaloneLinux64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneLinux64

build-StandaloneOSX:
  image: teuteuf/unity:latest_Mac
  <<: *build
  variables:
    BUILD_TARGET: StandaloneOSX

build-StandaloneWindows64:
  image: teuteuf/unity:latest_Windows
  <<: *build
  variables:
    BUILD_TARGET: StandaloneWindows64

build-Android:
  image: teuteuf/unity-androidsdk:latest
  <<: *build
  variables:
    BUILD_TARGET: Android

generate-apk:
  image: teuteuf/gradle-androidsdk:latest
  stage: post-build
  script: |
    cd ./Builds/Android/SpotTheDefuser/SpotTheDefuser_Unity
    ls -ahl
    gradle assembleRelease
    ls -ahl
    find . -name '*.apk'
    ls -ahl build/outputs/apk/
  retry: 2
  artifacts:
    name: "$BUILD_NAME $CI_PIPELINE_IID $BUILD_TARGET"
    paths:
    - ./Builds/Android/$BUILD_NAME/$BUILD_NAME/build/outputs/apk/release/$BUILD_NAME-release.apk
    expire_in: 1 day
